#!/bin/bash

# Built to set up check50 for use in 2018 - 2019
# does not run oob, will need to be made executable "chmod +x install"

# check for correct number of arguments
if [ "$#" -ne "0" ]; then
    echo "Usage: $0"
    exit
fi

# install CS50's check50 with pip
pip install check50

# find out if user is ubuntu or mac
read -p "Are you on Ubuntu or a Mac? (u/m) " u_or_m

# touch - check if file exists, else make that file
# echo - literally echo back the argument
# >> - append the output of the left to the file on the right
# source - source the environment's configuration and variables from the file passed as the argument
if [ "$u_or_m" == "m" ]; then
    touch ~/.bash_profile
    echo "check () { check50 \"\$1\"@harvard-crimson/checks; }" >> ~/.bash_profile
    source ~/.bash_profile
else
    touch ~/.bashrc
    echo "check () { check50 \"\$1\"@harvard-crimson/checks; }" >> ~/.bashrc
    source ~/.bashrc
fi

read -p "What is your Github username? " username
git config --global credential.https://github.com/submit50.username $username
