Vagrant.require_version ">= 1.7"

Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/trusty64'
  config.vm.hostname = 'local.thecrimson.com'
  config.vm.provision 'shell', path: 'bootstrap_vagrant.sh'
  config.vm.network 'private_network', ip: '172.16.10.10'
  config.vm.provider 'virtualbox' do |vb|
    vb.memory = ENV['CRIMSONONLINE_VM_MEMORY'] || 1024
  end

  config.ssh.forward_agent = true
end
